workflow:
  rules:
    # - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    #   when: always
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

variables:
  ENVIRONMENT: dev

include:
  - local: /gitlab-ci/aws/cdk.yml

quasar_build_pwa (dev):
  extends: .quasar_build_pwa

cdk_deploy (dev):
  extends: .cdk_deploy

collectstatic (dev):
  extends: .collectstatic

migrate (dev):
  extends: .migrate

createsuperuser (dev):
  extends: .createsuperuser

cdk_destroy (dev):
  extends: .cdk_destroy
