version: "3.7"

services:
  vuepress:
    container_name: vuepress
    build:
      context: ../documentation
    command: ["sh", "/app/start_dev.sh"]
    ports:
      - "8082:8080"
      - "8081:8081"
    volumes:
      - ../documentation:/app/
    environment:
      CI_PROJECT_URL: ${CI_PROJECT_URL}
