# Generated by Django 2.2 on 2020-01-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_auto_20200126_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source_file",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to="banking.StatementFile",
            ),
            preserve_default=False,
        ),
    ]
